/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidadCostos;

import java.text.DecimalFormat;
import static javax.management.Query.gt;
import static javax.management.Query.lt;

/**
 *
 * @author Dario
 */
public class conCostos extends javax.swing.JInternalFrame {

    /**
     * Creates new form conCostos
     */
    public conCostos() {
        initComponents();
        txt_costoUnitarioCosteo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_GastoOperacionCosteo = new javax.swing.JTextField();
        txt_gastoTransporteCosteo = new javax.swing.JTextField();
        txt_costoUnitarioCosteo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_calcularCosteo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Costeo");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Gastos de Operacion:");

        jLabel2.setText("Gastos de Transporte:");

        jLabel3.setText("Costo Unitario:");

        txt_GastoOperacionCosteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GastoOperacionCosteoActionPerformed(evt);
            }
        });
        txt_GastoOperacionCosteo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_GastoOperacionCosteoKeyTyped(evt);
            }
        });

        txt_gastoTransporteCosteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gastoTransporteCosteoActionPerformed(evt);
            }
        });
        txt_gastoTransporteCosteo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_gastoTransporteCosteoKeyTyped(evt);
            }
        });

        txt_costoUnitarioCosteo.setEditable(false);
        txt_costoUnitarioCosteo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_costoUnitarioCosteo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_costoUnitarioCosteo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_costoUnitarioCosteoKeyTyped(evt);
            }
        });

        btn_calcularCosteo.setText("Calcular");
        btn_calcularCosteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularCosteoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_calcularCosteo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(txt_costoUnitarioCosteo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_GastoOperacionCosteo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gastoTransporteCosteo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_GastoOperacionCosteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_gastoTransporteCosteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btn_calcularCosteo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_costoUnitarioCosteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_GastoOperacionCosteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GastoOperacionCosteoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GastoOperacionCosteoActionPerformed

    private void btn_calcularCosteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularCosteoActionPerformed
      String GO_S = txt_GastoOperacionCosteo.getText();
      String GT_S = txt_gastoTransporteCosteo.getText();
      
      double GO = 0;
      double GT = 0;
      double CU = 0;
      String CU2 = "";
      double driverGO = 0.000025;
      double driverGT = 0.02;
      double CC = 0;
              
      if(GO_S.length() != 0 && GT_S.length() != 0){
          GO = Double.valueOf(GO_S);
          GT = Double.valueOf(GT_S);
          if(GT != 0 && GO!=0){
            CC = 2;
            CU = (driverGO * GO) + (driverGT * GT) + CC;
            
            DecimalFormat df = new DecimalFormat("0.00");
            CU2 = df.format(CU);
            //CU = Math.rint((CU*2)/2);
            }
          
      }
      
      txt_costoUnitarioCosteo.setText(String.valueOf(CU2));
    }//GEN-LAST:event_btn_calcularCosteoActionPerformed

    private void txt_gastoTransporteCosteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gastoTransporteCosteoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gastoTransporteCosteoActionPerformed

    private void txt_GastoOperacionCosteoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GastoOperacionCosteoKeyTyped
        char car = evt.getKeyChar();
        if( car<'0' || car>'9'){
            if(car!='.'){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_GastoOperacionCosteoKeyTyped

    private void txt_gastoTransporteCosteoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_gastoTransporteCosteoKeyTyped
        char car = evt.getKeyChar();
        if( car<'0' || car>'9'){
            if(car!='.'){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_gastoTransporteCosteoKeyTyped

    private void txt_costoUnitarioCosteoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_costoUnitarioCosteoKeyTyped
        char car = evt.getKeyChar();
        if( car<'0' || car>'9'){
            if(car!='.'){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_costoUnitarioCosteoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcularCosteo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_GastoOperacionCosteo;
    private javax.swing.JTextField txt_costoUnitarioCosteo;
    private javax.swing.JTextField txt_gastoTransporteCosteo;
    // End of variables declaration//GEN-END:variables
}

