
package interfaces.realizarTransaccion;

import conexion.Conexion;
import sistemacontable.SistemaContable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import sistemacontable.Cuenta;

/**
 * @author Dario
 */
public class frm_PagoMantenimiento extends javax.swing.JInternalFrame {

    private Cuenta cuenta;
    ArrayList<Cuenta> formaPago = new ArrayList<Cuenta>();
    
    public void enviarCuenta(Cuenta cuenta){
        this.cuenta = cuenta;
    }
    public frm_PagoMantenimiento() {
        initComponents();
        llenarCmbFormaPago();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_frmPagoMantenimiento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_tipoPagoMantenimiento = new javax.swing.JComboBox();
        txt_cantidadContadoMantenimiento = new javax.swing.JTextField();
        txt_cantidadCreditoMantenimiento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descripcionMantenimiento = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pago de Mantenimiento");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_frmPagoMantenimiento.setText("Aceptar");
        btn_frmPagoMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmPagoMantenimientoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Pago:");

        jLabel2.setText("Cantidad Contado:");

        jLabel3.setText("Cantidad Credito:");

        jLabel4.setText("Descripcion:");

        txt_cantidadContadoMantenimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadContadoMantenimientoKeyTyped(evt);
            }
        });

        txt_cantidadCreditoMantenimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadCreditoMantenimientoKeyTyped(evt);
            }
        });

        txt_descripcionMantenimiento.setColumns(20);
        txt_descripcionMantenimiento.setRows(5);
        jScrollPane2.setViewportView(txt_descripcionMantenimiento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_frmPagoMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cantidadCreditoMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(cmb_tipoPagoMantenimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_cantidadContadoMantenimiento))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addContainerGap(289, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_tipoPagoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_cantidadContadoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cantidadCreditoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btn_frmPagoMantenimiento)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(30, 30, 30)
                    .addComponent(jLabel2)
                    .addContainerGap(232, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_frmPagoMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmPagoMantenimientoActionPerformed
        try {
            SistemaContable sistema = new SistemaContable();
            
            String pago = obtenerCodigoFormaPago();
            
            sistema.pagoMantenimiento(cuenta, txt_cantidadContadoMantenimiento.getText(),txt_cantidadCreditoMantenimiento.getText(), pago, 1);
            JOptionPane.showMessageDialog(this, "Transacción Exitosa");
            limpiarForm();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un problema al momentos de Realizar la transacción");
        }
        limpiarForm();
    }//GEN-LAST:event_btn_frmPagoMantenimientoActionPerformed

    private void txt_cantidadContadoMantenimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadContadoMantenimientoKeyTyped
        char car = evt.getKeyChar();
        if( car<'0' || car>'9'){
            if(car!='.'){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_cantidadContadoMantenimientoKeyTyped

    private void txt_cantidadCreditoMantenimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadCreditoMantenimientoKeyTyped
        char car = evt.getKeyChar();
        if( car<'0' || car>'9'){
            if(car!='.'){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_cantidadCreditoMantenimientoKeyTyped
    void limpiarForm(){
        txt_cantidadContadoMantenimiento.setText("");
        txt_cantidadCreditoMantenimiento.setText("");
        txt_descripcionMantenimiento.setText("");
    }
    void llenarCmbFormaPago(){
        Conexion SIC = new Conexion();
        Connection con = SIC.conexion();
        
        String sentenciaSQL= "SELECT codigo, nombre FROM catalogo_cuentas WHERE codigo LIKE '111-01' OR codigo LIKE '111-02' OR codigo LIKE '111-03-01'";
        
        try {
            Statement statement = con.createStatement();
            ResultSet resultado = statement.executeQuery(sentenciaSQL);
            
            while (resultado.next()) {
                    Cuenta cuenta = new Cuenta();
                    cuenta.setNombre( resultado.getString("nombre") );
                    cuenta.setCodigo(resultado.getString("codigo") );
                    formaPago.add(cuenta);
                    cmb_tipoPagoMantenimiento.addItem(cuenta.getNombre());                     
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al llenar Tipo de Pago");
        }
    }
    ///METODO QUE RETORNA EL CODIGO DE LA FORMA DE PAGO SELECCIONADA
    String obtenerCodigoFormaPago(){
        String cmbSeleccionado="",codigo="";
        cmbSeleccionado = (String)cmb_tipoPagoMantenimiento.getSelectedItem();
        
        for (Cuenta C : formaPago) {
            if(C.getNombre().equals(cmbSeleccionado)){
                codigo = C.getCodigo();
            }
        }
        return codigo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_frmPagoMantenimiento;
    private javax.swing.JComboBox cmb_tipoPagoMantenimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_cantidadContadoMantenimiento;
    private javax.swing.JTextField txt_cantidadCreditoMantenimiento;
    private javax.swing.JTextArea txt_descripcionMantenimiento;
    // End of variables declaration//GEN-END:variables
}
