
package interfaces.realizarTransaccion;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import sistemacontable.Cuenta;
import sistemacontable.SistemaContable;

/**
 * @author Dario
 */
public class frm_PagosCobros extends javax.swing.JInternalFrame {

    private Cuenta cuenta;
    ArrayList<Cuenta> formaPago = new ArrayList<Cuenta>();
    
    public void enviarCuenta(Cuenta cuenta){
        this.cuenta = cuenta;
    }
    public frm_PagosCobros() {
        initComponents();
        llenarCmbFormaPago();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_frmPagosCobros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmb_formaPagoPagosCobros = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txt_cantidadPagosCobros = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcionPagosCobros = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pagos y Cobros");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_frmPagosCobros.setText("Aceptar");
        btn_frmPagosCobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmPagosCobrosActionPerformed(evt);
            }
        });

        jLabel1.setText("Forma de Pago: ");

        jLabel2.setText("Cantidad: ");

        txt_cantidadPagosCobros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadPagosCobrosKeyTyped(evt);
            }
        });

        jLabel3.setText("Descripcion:");

        txt_descripcionPagosCobros.setColumns(20);
        txt_descripcionPagosCobros.setRows(5);
        jScrollPane1.setViewportView(txt_descripcionPagosCobros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_frmPagosCobros, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_formaPagoPagosCobros, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_cantidadPagosCobros, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(btn_frmPagosCobros)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmb_formaPagoPagosCobros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_cantidadPagosCobros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_frmPagosCobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmPagosCobrosActionPerformed
        try {
                SistemaContable S = new SistemaContable();
                String pago = obtenerCodigoFormaPago();
                S.pago(this.cuenta, txt_cantidadPagosCobros.getText(),  pago, 1);
            
                JOptionPane.showMessageDialog(this, "Transacción Exitosa");
                limpiarForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un problema al momentos de Realizar la transacción");
        }
    }//GEN-LAST:event_btn_frmPagosCobrosActionPerformed

    private void txt_cantidadPagosCobrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadPagosCobrosKeyTyped
        char car = evt.getKeyChar();
        if( car<'0' || car>'9'){
            if(car!='.'){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_cantidadPagosCobrosKeyTyped
    void limpiarForm(){
        txt_cantidadPagosCobros.setText("");
        txt_descripcionPagosCobros.setText("");
    }
    void llenarCmbFormaPago(){
        Conexion SIC = new Conexion();
        Connection con = SIC.conexion();
        
        String sentenciaSQL= "SELECT codigo, nombre FROM catalogo_cuentas WHERE codigo LIKE '111-01' OR codigo LIKE '111-02' OR codigo LIKE '111-03-01'";
        
        try {
            Statement statement = con.createStatement();
            ResultSet resultado = statement.executeQuery(sentenciaSQL);
            
            while (resultado.next()) {
                    Cuenta cuenta = new Cuenta();
                    cuenta.setNombre( resultado.getString("nombre") );
                    cuenta.setCodigo(resultado.getString("codigo") );
                    formaPago.add(cuenta);
                    
                    cmb_formaPagoPagosCobros.addItem(cuenta.getNombre());
                    
            }
        } catch (Exception e) {
        }
    }
    
    ///METODO QUE RETORNA EL CODIGO DE LA FORMA DE PAGO SELECCIONADA
    String obtenerCodigoFormaPago(){
        String cmbSeleccionado="",codigo="";
        cmbSeleccionado = (String)cmb_formaPagoPagosCobros.getSelectedItem();
        
        for (Cuenta C : formaPago) {
            if(C.getNombre().equals(cmbSeleccionado)){
                codigo = C.getCodigo();
            }
        }
        return codigo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_frmPagosCobros;
    public static javax.swing.JComboBox cmb_formaPagoPagosCobros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txt_cantidadPagosCobros;
    public static javax.swing.JTextArea txt_descripcionPagosCobros;
    // End of variables declaration//GEN-END:variables
}
