
package interfaces.realizarTransaccion;

import conexion.Conexion;
import interfaces.Escritorio;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemacontable.Cuenta;
import sistemacontable.SistemaContable;

/**
 * @author Dario
 */
public class trn_AumentoActivo extends javax.swing.JInternalFrame {

    public trn_AumentoActivo() {
        initComponents();
    }
    ArrayList<Cuenta> cuentas = new ArrayList<Cuenta>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_continuarAumentoActivo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tipoAumentoActivo = new javax.swing.JTable();
        btn_seleccionAumentoActivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cuentaAumentoActivo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Aumento de Activo");

        btn_continuarAumentoActivo.setText("Continuar");
        btn_continuarAumentoActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuarAumentoActivoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_tipoAumentoActivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Seguro"},
                {"Prestamos"},
                {"Inversiones"},
                {"Terrenos"},
                {"Instalaciones"}
            },
            new String [] {
                "Transaccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_tipoAumentoActivo);

        btn_seleccionAumentoActivo.setText(">>");
        btn_seleccionAumentoActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionAumentoActivoActionPerformed(evt);
            }
        });

        tbl_cuentaAumentoActivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cuenta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_cuentaAumentoActivo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_seleccionAumentoActivo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(btn_seleccionAumentoActivo))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_continuarAumentoActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_continuarAumentoActivo)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionAumentoActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionAumentoActivoActionPerformed
        Escritorio.limpiarTabla(tbl_cuentaAumentoActivo);
        cuentas.clear();
        int trn = tbl_tipoAumentoActivo.getSelectedRow();
        Conexion SIC = new Conexion();
        Connection con = SIC.conexion();
        
        pintarTblCuenta(trn, con);
    }//GEN-LAST:event_btn_seleccionAumentoActivoActionPerformed

    private void btn_continuarAumentoActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarAumentoActivoActionPerformed
        if(tbl_cuentaAumentoActivo.getSelectedRow() != -1  ){
            frm_AumentoActivo frm_aumentoActivo = new frm_AumentoActivo();
   
            
            int cnt = tbl_cuentaAumentoActivo.getSelectedRow();
            frm_aumentoActivo.enviarCuenta(cuentas.get(cnt));
            Escritorio.Escritorio.add(frm_aumentoActivo);
            frm_aumentoActivo.setLocation(Escritorio.Escritorio.getWidth()/2-frm_aumentoActivo.getWidth()/2, Escritorio.Escritorio.getHeight()/2-frm_aumentoActivo.getHeight()/2);
            frm_aumentoActivo.show();
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Cuenta para continuar con la transaccion");
        }
    }//GEN-LAST:event_btn_continuarAumentoActivoActionPerformed
    
    private void pintarTblCuenta(int trn, Connection con){
        DefaultTableModel tbl_Cuenta = (DefaultTableModel) tbl_cuentaAumentoActivo.getModel();
        
        String sentenciaSQL= "";
        switch(trn){
            case 0: 
                sentenciaSQL = "select *from catalogo_cuentas where codigo='119-01'";
            break;
            case 1:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='221-01'";
            break;
            case 2:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='118-01'";
            break;
            case 3:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='121-01-01'";
            break;
            case 4:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='121-02'";
            break;

        }
        
        try {
            
            Statement statement = con.createStatement();
            ResultSet resultado = statement.executeQuery(sentenciaSQL);
            
            while (resultado.next()) {
                    Cuenta cuenta = new Cuenta();
                    cuenta.setCodigo( resultado.getString("codigo") );
                    cuenta.setNombre( resultado.getString("nombre") );
                    cuentas.add(cuenta);
                    
                    tbl_Cuenta.addRow(new Object[]{cuenta.getCodigo(),cuenta.getNombre()});
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No exiten Cuentas asociadas a esta Transaccion");
          }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continuarAumentoActivo;
    private javax.swing.JButton btn_seleccionAumentoActivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_cuentaAumentoActivo;
    private javax.swing.JTable tbl_tipoAumentoActivo;
    // End of variables declaration//GEN-END:variables
}
