
package interfaces.realizarTransaccion;

import conexion.Conexion;
import interfaces.Escritorio;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemacontable.Cuenta;
import sistemacontable.SistemaContable;

/**
 * @author Dario
 */
public class trn_PagoMantenimiento extends javax.swing.JInternalFrame {

    
    public trn_PagoMantenimiento() {
        initComponents();
    }
    ArrayList<Cuenta> cuentas = new ArrayList<Cuenta>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_continuarPagoMantenimiento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_seleccionPagoMantenimiento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tipoPagoMantenimiento = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cuentaPagoMantenimiento = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pago de Mantenimiento");

        btn_continuarPagoMantenimiento.setText("Continuar");
        btn_continuarPagoMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuarPagoMantenimientoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_seleccionPagoMantenimiento.setText(">>");
        btn_seleccionPagoMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionPagoMantenimientoActionPerformed(evt);
            }
        });

        tbl_tipoPagoMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Mantenimiento de Locales"},
                {"Mantenimiento de Vehiculos"},
                {"Mantenimiento de Mobiliario y Equipo"}
            },
            new String [] {
                "Transacciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_tipoPagoMantenimiento);

        tbl_cuentaPagoMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_cuentaPagoMantenimiento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_seleccionPagoMantenimiento)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(btn_seleccionPagoMantenimiento))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_continuarPagoMantenimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_continuarPagoMantenimiento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionPagoMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionPagoMantenimientoActionPerformed
        Escritorio.limpiarTabla(tbl_cuentaPagoMantenimiento);
        cuentas.clear();
        int trn = tbl_tipoPagoMantenimiento.getSelectedRow();
        Conexion SIC = new Conexion();
        Connection con = SIC.conexion();
        
        pintarTblCuenta(trn, con);
    }//GEN-LAST:event_btn_seleccionPagoMantenimientoActionPerformed

    private void btn_continuarPagoMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarPagoMantenimientoActionPerformed
        if(tbl_cuentaPagoMantenimiento.getSelectedRow() != -1  ){
            frm_PagoMantenimiento frm_pagoMantenimiento= new frm_PagoMantenimiento();
   
            
            int cnt = tbl_cuentaPagoMantenimiento.getSelectedRow();
            frm_pagoMantenimiento.enviarCuenta(cuentas.get(cnt));
            
            Escritorio.Escritorio.add(frm_pagoMantenimiento);
            frm_pagoMantenimiento.setLocation(Escritorio.Escritorio.getWidth()/2-frm_pagoMantenimiento.getWidth()/2, Escritorio.Escritorio.getHeight()/2-frm_pagoMantenimiento.getHeight()/2);
            frm_pagoMantenimiento.show();
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Cuenta para continuar con la transaccion");
        }
    }//GEN-LAST:event_btn_continuarPagoMantenimientoActionPerformed
    private void pintarTblCuenta(int trn, Connection con){
        DefaultTableModel tbl_Cuenta = (DefaultTableModel) tbl_cuentaPagoMantenimiento.getModel();
        
        String sentenciaSQL= "";
        switch(trn){
            case 0: 
                sentenciaSQL = "select *from catalogo_cuentas where codigo='412-19'";
            break;
            case 1:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='412-20'";
            break;
            case 2:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='412-21'";
            break;

        }
        
        try {
            
            Statement statement = con.createStatement();
            ResultSet resultado = statement.executeQuery(sentenciaSQL);
            
            while (resultado.next()) {
                    Cuenta cuenta = new Cuenta();
                    cuenta.setCodigo( resultado.getString("codigo") );
                    cuenta.setNombre( resultado.getString("nombre") );
                    cuentas.add(cuenta);
                    
                    tbl_Cuenta.addRow(new Object[]{cuenta.getCodigo(),cuenta.getNombre()});
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No exiten Cuentas asociadas a esta Transaccion");
          }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continuarPagoMantenimiento;
    private javax.swing.JButton btn_seleccionPagoMantenimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_cuentaPagoMantenimiento;
    private javax.swing.JTable tbl_tipoPagoMantenimiento;
    // End of variables declaration//GEN-END:variables
}
