
package interfaces.realizarTransaccion;

import conexion.Conexion;
import interfaces.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemacontable.*;

/**
 * @author Dario
 */
public class trn_Ajustes extends javax.swing.JInternalFrame {

    public trn_Ajustes() {
        initComponents();
    }
    
    ArrayList<Cuenta> cuentas = new ArrayList<Cuenta>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tipoAjustes = new javax.swing.JTable();
        btn_seleccionAjustes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cuentaAjustes = new javax.swing.JTable();
        btn_continuarAjustes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Ajustes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_tipoAjustes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Depreciacion"},
                {"Cuenta Incobrable"},
                {"Gastos pagados por Anticipado"},
                {"Gastos Acumulados"},
                {"Ingreso de Inventario Final"}
            },
            new String [] {
                "Transaccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_tipoAjustes);

        btn_seleccionAjustes.setText(">>");
        btn_seleccionAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionAjustesActionPerformed(evt);
            }
        });

        tbl_cuentaAjustes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cuenta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_cuentaAjustes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_seleccionAjustes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_seleccionAjustes))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_continuarAjustes.setText("Continuar");
        btn_continuarAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuarAjustesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_continuarAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_continuarAjustes)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionAjustesActionPerformed
        Escritorio.limpiarTabla(tbl_cuentaAjustes);
        cuentas.clear();
        int trn = tbl_tipoAjustes.getSelectedRow();
        Conexion SIC = new Conexion();
        Connection con = SIC.conexion();
        
        pintarTblCuenta(trn, con);
    }//GEN-LAST:event_btn_seleccionAjustesActionPerformed

    private void btn_continuarAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarAjustesActionPerformed
        if(tbl_cuentaAjustes.getSelectedRow() != -1  ){
            frm_Ajustes frm_ajustes = new frm_Ajustes();
   
            
            int cnt = tbl_cuentaAjustes.getSelectedRow();
            frm_ajustes.enviarCuenta(cuentas.get(cnt));
            
            Escritorio.Escritorio.add(frm_ajustes);
            frm_ajustes.setLocation(Escritorio.Escritorio.getWidth()/2-frm_ajustes.getWidth()/2, Escritorio.Escritorio.getHeight()/2-frm_ajustes.getHeight()/2);
            frm_ajustes.show();
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Cuenta para continuar con la transaccion");
        }
        
    }//GEN-LAST:event_btn_continuarAjustesActionPerformed
    
    private void pintarTblCuenta(int trn, Connection con){
        DefaultTableModel tbl_Cuenta = (DefaultTableModel) tbl_cuentaAjustes.getModel();
        
        String sentenciaSQL= "";
        switch(trn){
            case 0: 
                sentenciaSQL = "select *from catalogo_cuentas where codigo='121-01' OR codigo='121-02' OR codigo='121-03' OR codigo='121-04'";
            break;
            case 1://Pueba
                sentenciaSQL = "select *from catalogo_cuentas where codigo='112-05'";
            break;
            case 2:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='119-04' OR codigo='119-01' OR codigo='119-05' OR codigo='412-10' OR codigo='119-02'";
            break;
            case 3:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='121-05'";
            break;
            case 4:
                sentenciaSQL = "select *from catalogo_cuentas where codigo='117-07'";
            break;
            
        }
        
        try {
            
            Statement statement = con.createStatement();
            ResultSet resultado = statement.executeQuery(sentenciaSQL);
            
            while (resultado.next()) {
                    Cuenta cuenta = new Cuenta();
                    cuenta.setCodigo( resultado.getString("codigo") );
                    cuenta.setNombre( resultado.getString("nombre") );
                    cuentas.add(cuenta);
                    
                    tbl_Cuenta.addRow(new Object[]{cuenta.getCodigo(),cuenta.getNombre()});
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No exiten Cuentas asociadas a esta Transacion");
          }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continuarAjustes;
    private javax.swing.JButton btn_seleccionAjustes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_cuentaAjustes;
    private javax.swing.JTable tbl_tipoAjustes;
    // End of variables declaration//GEN-END:variables
}
